# Container Structure Tests for API Gateway
# https://github.com/GoogleContainerTools/container-structure-test

schemaVersion: 2.0.0

metadataTest:
  labels:
    - key: "org.opencontainers.image.title"
      value: "API Gateway"
    - key: "org.opencontainers.image.vendor"
      value: "Stashfi"
  exposedPorts: ["8080"]
  workdir: "/app"
  user: "65532"  # distroless nonroot user ID

fileExistenceTests:
  - name: "API Gateway binary exists"
    path: "/app/api-gateway"
    shouldExist: true
    permissions: "-rwxr-xr-x"

  - name: "No package managers (apt)"
    path: "/usr/bin/apt"
    shouldExist: false

  - name: "No package managers (apt-get)"
    path: "/usr/bin/apt-get"
    shouldExist: false

  - name: "No package managers (dpkg)"
    path: "/usr/bin/dpkg"
    shouldExist: false

  - name: "No shell (sh)"
    path: "/bin/sh"
    shouldExist: false

  - name: "No shell (bash)"
    path: "/bin/bash"
    shouldExist: false

  - name: "No shell (dash)"
    path: "/bin/dash"
    shouldExist: false

  - name: "SSL certificates present"
    path: "/etc/ssl/certs/ca-certificates.crt"
    shouldExist: true

fileContentTests:
  - name: "Binary is statically linked"
    path: "/app/api-gateway"
    expectedContents: ["ELF"]
    excludedContents: ["libc.so"]

commandTests:
  # Note: Command tests are limited in distroless as there's no shell
  # The binary must handle all functionality directly
  - name: "Binary executes successfully"
    command: "/app/api-gateway"
    args: ["--help"]
    exitCode: 0

  - name: "Version flag works"
    command: "/app/api-gateway"
    args: ["--version"]
    exitCode: 0
