# Root-level mise configuration for the Stashfi monorepo

## Settings
##
# Enable the lockfile so that mise generates and uses a `mise.lock` file.
[settings]
lockfile = true

## Tools
##
# Shared tool versions used across all services in the repository.  This ensures
# every contributor and CI job uses the same Node, Python, Go and tooling versions.
[tools]
node    = "22.18.0"  # LTS release for Node.js
go      = "1.23.4"   # Latest stable Go version
uv      = "0.8.12"   # Universal virtualenv manager
helm    = "3.16.3"   # Kubernetes package manager
kubectl = "1.31.3"   # Kubernetes CLI
minikube = "1.34.0"  # Local Kubernetes cluster runtime

##
# This root file intentionally contains only shared configuration.  Service‑specific
# tasks and overrides live in their respective `services/<name>/mise.toml` files.
