# Root-level mise configuration for the Stashfi monorepo

[settings]
lockfile = true

[tools]
# Core development runtimes
node = "latest"
go   = "latest"
uv   = "latest"

# Kubernetes and Helm tooling
helm       = "3.18.6"
kubectl    = "1.31.3"
minikube   = "1.35.0"
kind       = "0.30.0"           # Match .github/VERSIONS.md
kubeconform = "0.7.0"           # Modern replacement for deprecated kubeval, with ARM support
pluto      = "5.22.5"

# Linters and formatters
#hadolint = "latest"      # Dockerfile linter - No Darwin arm_64 version available
shellcheck = "latest"   # Shell script analyzer
shfmt = "latest"        # Shell script formatter
yq = "4.47.1"           # YAML/JSON processor
"pipx:yamllint" = "latest"
"npm:@commitlint/cli" = "latest"

# Git hooks and commit management
"pipx:pre-commit" = "latest"
"pipx:commitizen" = "latest"

# Go tooling
# Corrected gitleaks path to use the canonical Go module import path
"go:github.com/zricethezav/gitleaks/v8" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

# Security scanners
"pipx:detect-secrets" = "latest"
"go:github.com/securego/gosec/v2/cmd/gosec" = "latest"
"go:github.com/google/osv-scanner/cmd/osv-scanner" = "latest"


# NOTE: "@commitlint/cli" is now managed in the root package.json
