# Minimal GolangCI-Lint configuration for API Gateway

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/stashfi/api-gateway
