openapi: 3.1.0
info:
  title: Stashfi API Gateway
  description: API Gateway service for the Stashfi trading platform
  version: 0.1.0
  contact:
    name: Stashfi Team

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: http://localhost:32080
    description: Minikube Kong proxy

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API gateway service
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /ready:
    get:
      summary: Readiness check endpoint
      description: Returns whether the service is ready to accept requests
      operationId: getReady
      tags:
        - Health
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyResponse'

  /api/v1/status:
    get:
      summary: Service status endpoint
      description: Returns detailed status information about the API gateway service
      operationId: getStatus
      tags:
        - Status
      responses:
        '200':
          description: Service status information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy]
          description: Health status of the service
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp of the health check

    ReadyResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [ready]
          description: Readiness status of the service
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp of the readiness check

    StatusResponse:
      type: object
      required:
        - service
        - version
        - status
        - timestamp
      properties:
        service:
          type: string
          description: Name of the service
          example: api-gateway
        version:
          type: string
          description: Version of the service
          example: 0.1.0
        status:
          type: string
          enum: [operational, degraded, down]
          description: Operational status of the service
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp of the status check

tags:
  - name: Health
    description: Health and readiness checks
  - name: Status
    description: Service status information
