name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api-gateway

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Build
        run: go build -v .

      - name: Lint
        run: |
          go vet ./...
          gofmt -l -d .

  docker-build:
    runs-on: ubuntu-latest
    needs: api-gateway

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/api-gateway
          file: ./services/api-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: stashfi/api-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT=${{ github.sha }}

  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.16.3'

      - name: Lint Helm charts
        run: |
          helm version
          helm lint infra/helm/kong
          # Add other charts as they're created
