name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api-gateway

    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: Install tools from mise.toml
        run: |
          # Copy root mise files to service directory
          cp ../../mise.toml .
          cp ../../mise.lock . 2>/dev/null || true
          # Install tools (will use .mise.toml if present, else mise.toml)
          mise install
          mise list

      - name: Run tests
        run: |
          eval "$(mise activate bash)"
          go test -v -race -coverprofile=coverage.out ./...

      - name: Build
        run: |
          eval "$(mise activate bash)"
          go build -v .

      - name: Lint
        run: |
          eval "$(mise activate bash)"
          go vet ./...
          gofmt -l -d .

  docker-build:
    runs-on: ubuntu-latest
    needs: api-gateway

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/api-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: stashfi/api-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
            GIT_COMMIT=${{ github.sha }}

  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install Helm via mise
        run: |
          # Add helm to mise.toml if not present
          if ! grep -q "^helm = " mise.toml; then
            echo 'helm = "3.16.3"' >> mise.toml
          fi
          mise install helm
          eval "$(mise activate bash)"
          helm version

      - name: Lint Helm charts
        run: |
          eval "$(mise activate bash)"
          helm lint infra/helm/kong
          # Add other charts as they're created
