name: supply-chain-attestation (Migrated)

on:
  # Copy triggers from original workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  # Example: Go testing
  test:
    name: Test
    uses: ./.github/workflows/_reusable-go-test.yml
    with:
      service_path: ./services/supply-chain-attestation
      go_version: '1.25.1'
      coverage_threshold: 70

  # Example: Security scanning
  security:
    name: Security
    uses: ./.github/workflows/_reusable-security-scan.yml
    with:
      language: go
      scan_path: ./services/supply-chain-attestation

  # Example: Docker build
  docker:
    name: Build
    needs: [test]
    uses: ./.github/workflows/_reusable-docker-build.yml
    with:
      image_name: supply-chain-attestation
      dockerfile_path: ./services/supply-chain-attestation
      push: ${{ github.ref == 'refs/heads/main' }}

  # Example: Helm validation
  helm:
    name: Helm
    uses: ./.github/workflows/_reusable-helm-validate.yml
    with:
      chart_path: ./infra/helm/supply-chain-attestation
